describe('Tugas 4 - Belajar Cypress', function(){
    it('login', function(){
        cy.bukaUrl()
        cy.get('#login2').click()
        cy.wait(1000)
        cy.get('#loginusername').type('testsaiful').should('have.value','testsaiful')
        cy.get('#loginpassword').type('testsaiful098').should('have.value','testsaiful098')
        cy.wait(1000)
        cy.get('#logInModal > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
        cy.contains('testsaiful').should('exist')
    }),
    it('buy phone', function(){
        cy.get(':nth-child(7) > .card > .card-block > .card-title > .hrefch').click()
        cy.wait(5000)
        cy.get('.col-sm-12 > .btn').click()
        cy.wait(5000)
        cy.get('#cartur').click()
        cy.get('.active > .nav-link').click()
        // cy.get('[onclick="byCat('notebook')"]').click()
        cy.wait(2000)
        cy.get(':nth-child(4) > .card > .card-block > .card-title > .hrefch').click()
        cy.get('.col-sm-12 > .btn').click()
        cy.get(':nth-child(4) > .nav-link').click()
        cy.get('.active > .nav-link').click()
        // cy.get('[onclick="byCat('monitor')"]').click()
        cy.get(':nth-child(1) > .card > .card-block > .card-title > .hrefch').click()
        cy.get('.col-sm-12 > .btn').click()
        cy.get('#cartur').click()
        cy.get('.col-lg-1 > .btn').click()
        cy.wait(1000)
        cy.get('#name').type('saifulbeli').should('have.value','saifulbeli')
        cy.get('#country').type('Indonesia').should('have.value','Indonesia')
        cy.get('#city').type('Batam').should('have.value','Batam')
        cy.get('#card').type('0129384756').should('have.value','0129384756')
        cy.get('#month').type('August').should('have.value','August')
        cy.get('#year').type('2021').should('have.value','2021')
        cy.wait(2000)
        cy.get('#orderModal > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
        cy.wait(10000)
        cy.get('.confirm').click()

    })
})